server.port=8080

spring.application.name=enigma-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/enigma
spring.datasource.username=postgres
spring.datasource.password=postgresql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.time-zone=UTC

management.endpoints.web.exposure.include=health,info

app.questions.pdf-path=${QUESTION_PDF_PATH:C:/Users/karti/Downloads/Collated Mock Question - SET 2.pdf}
app.questions.default-limit=20